// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn2vBZpmDcZlssIyOr5ApWgy2uK344nmw',
    appId: '1:517961716843:web:70835e80b97d1bea5ccd2e',
    messagingSenderId: '517961716843',
    projectId: 'dct-supportlink',
    authDomain: 'dct-supportlink.firebaseapp.com',
    databaseURL: 'https://dct-supportlink-default-rtdb.firebaseio.com',
    storageBucket: 'dct-supportlink.firebasestorage.app',
    measurementId: 'G-YHPXBPHZ2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxM8UoVrmVtRo00MmNaZw0gj_wXYO0aJE',
    appId: '1:517961716843:android:57167d7c16859ca45ccd2e',
    messagingSenderId: '517961716843',
    projectId: 'dct-supportlink',
    databaseURL: 'https://dct-supportlink-default-rtdb.firebaseio.com',
    storageBucket: 'dct-supportlink.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLeQToAB_gx9B80C7RJfkHpHOEB1YV54k',
    appId: '1:517961716843:ios:029cae1fc98a3b5c5ccd2e',
    messagingSenderId: '517961716843',
    projectId: 'dct-supportlink',
    databaseURL: 'https://dct-supportlink-default-rtdb.firebaseio.com',
    storageBucket: 'dct-supportlink.firebasestorage.app',
    iosBundleId: 'com.example.dctSupportlinkMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLeQToAB_gx9B80C7RJfkHpHOEB1YV54k',
    appId: '1:517961716843:ios:029cae1fc98a3b5c5ccd2e',
    messagingSenderId: '517961716843',
    projectId: 'dct-supportlink',
    databaseURL: 'https://dct-supportlink-default-rtdb.firebaseio.com',
    storageBucket: 'dct-supportlink.firebasestorage.app',
    iosBundleId: 'com.example.dctSupportlinkMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn2vBZpmDcZlssIyOr5ApWgy2uK344nmw',
    appId: '1:517961716843:web:eb0424a8414cee815ccd2e',
    messagingSenderId: '517961716843',
    projectId: 'dct-supportlink',
    authDomain: 'dct-supportlink.firebaseapp.com',
    databaseURL: 'https://dct-supportlink-default-rtdb.firebaseio.com',
    storageBucket: 'dct-supportlink.firebasestorage.app',
    measurementId: 'G-9S21Z1Z38W',
  );

}